### DISCUSSION TITLE
posts/cloud-init-cloud-image/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#194] [Comments]
# posts/cloud-init-cloud-image/

Documentation for Techno Tim YouTube videos for all your copy pasta needs!

https://technotim.live/posts/cloud-init-cloud-image/

**Comment by B1GWH1T3** [comment]
Thanks Tim for the awesome guides!

Not sure if its just me but I get this error when trying to mount the disk

Successfully imported disk as 'unused0:fastboi:8000/vm-8000-disk-0.raw'
root@REDQUEENHQPVE1:~# qm set 8000 --scsihw virtio-scsi-pci --scsi0 fastboi:vm-8000-disk-0
unable to parse directory volume name 'vm-8000-disk-0'

What I found is for some reason it creates it under the VM ID
root@REDQUEENHQPVE1:~# qm set 8000 --scsihw virtio-scsi-pci --scsi0 fastboi:8000/vm-8000-disk-0.raw
update VM 8000: -scsi0 fastboi:8000/vm-8000-disk-0.raw -scsihw virtio-scsi-pci

Just a note for anyone struggling with that portion

**Comment by andriesh** [comment]
Awesome tutorial but to make it even better I would suggest to do this:
Before importing the image as disk to the VM you should install the *qemu-guest-tools* package like this:

Install necessary tools:
`apt install libguestfs-tools`

Then import install the package:
`virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent`

And don't forget to enable the agent in the settings to be able to see the IP of your newly created VM:
`qm set 8000 --agent 1,fstrim_cloned_disks=1`

**Reply by qeba** [reply]
If you are doing it, I think it will get the same `machine-id` for others cloned VM, and will get the same IP for it, any suggestion to prevent it to happen when making the template?

**Reply by qeba** [reply]
maybe to play safe, since each time when running the `virt-customize` it will give a machine-id, as below;
```
[   3.9] Setting the machine ID in /etc/machine-id
```
maybe can added this, after install that qemu agent. 
```
virt-customize -a focal-server-cloudimg-amd64.img --run-command "sudo truncate -s 0 /etc/machine-id /var/lib/dbus/machine-id"
```

so that machine ID will be clear and it will insert itself when boot up.

**Reply by MDHMatt** [reply]
just tried it without running the command to remove machine id and no issues with ip address ect

**Reply by stsc-14051** [reply]
Was running into issues with terraform because this tutorial does not install qemu-guest-agent. When attempting to run ` virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent` on the cloud image it looks like my proxmox server was having issues locating the ubuntu repos? 

Any Ideas how to fix this? do I need to add these ubuntu repos to my /etc/apt/sources.list on the proxmox server? 

```
root@proxmox:~# virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent
[   0.0] Examining the guest ...
[   3.7] Setting a random seed
virt-customize: warning: random seed could not be set for this type of 
guest
[   3.7] Installing packages: qemu-guest-agent
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package qemu-guest-agent
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package qemu-guest-agent
virt-customize: error: 
        export DEBIAN_FRONTEND=noninteractive
        apt_opts='-q -y -o Dpkg::Options::=--force-confnew'
        apt-get $apt_opts update
        apt-get $apt_opts install 'qemu-guest-agent'
      : command exited with an error

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
```

**Reply by stsc-14051** [reply]
Found the fix for my issue, removed my internal DNS from /etc/resolv.conf on my proxmox server and it was able to locate the repo and download qemu-guest-agent!

**Reply by Gabgobie** [reply]
Take a look at the comment I left a few minutes ago. That is my preferred way of adding packages to my machines and configuring more parameters to make sure everything is as it should be, no tinkering with the original image required.

**Comment by MDHMatt** [comment]
If the image file creates a too small of a hard drive space add this after downloading your image file (adds 2Gb to the drive)
> qemu-img resize jammy-server-cloudimg-amd64.img +2G

**Comment by FedorPRO** [comment]
Thanks Tim!

I am trying to automate the whole process and write a bash script for this. And I think it's worth making changes, as in the official example (https://pve.proxmox.com/wiki/Cloud-Init_Support#_preparing_cloud_init_templates)

"--scsihw virtio-scsi-pci " should be used in "qm create "

In this case, the correct controller will be used and the disk will connect to it without problems

Changes like this:
qm create 8000 --memory 2048 --core 2 --name ubuntu-cloud --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-pci 

qm set 8000 --scsi0 local-lvm:8000/vm-8000-disk-0.raw

**Reply by thisisbramiller** [reply]
bump!

**Reply by thisisbramiller** [reply]
Working through this problem now. I noticed there is a difference depending upon which filesystem you are deploying to. 
LVM-Thin works just fine and outputs as: vm-9000-disk-0
while NFS gets changed to: EX2Ultra:9000/vm-9000-disk-0.raw

**Comment by Gabgobie** [comment]
To further enhance this you can add a vendor config. With cloud-init you can attatch four config files, three of which proxmox will manage through the UI. The vendor config is unset but you can add one without compromising the UIs functionality. It also ensures that you still have a clean image that has never been booted which is not the case when you use ```virt-customize```. In the vendor config you can then use the full range of cloud-inits wealth of features.

First you will need to enable a snipplets storage on your PVE host.

Then you can add your vendor config there. I for example called mine the template-ID combined with a description of what it is: 100000-civendor.yaml

To give an example of how this can look, here is mine:
```cat /var/lib/vz/snippets/100000-civendor.yaml```

```
#cloud-config

# don't think these two are needed as cloud-init seems to update the machine on first boot anyways but I still left them in there because I didn't take the time to confirm
package_update: true
package_upgrade: true

# installing some exemplary packages

packages:
  - qemu-guest-agent
  - git

# making sure qemu-guest-agent is running
runcmd:
    - systemctl start qemu-guest-agent

timezone: "Continent/City"

ca_certs:
  # If present and set to True, the 'remove_defaults' parameter will either
  # disable all the trusted CA certifications normally shipped with
  # Alpine, Debian or Ubuntu. On RedHat, this action will delete those
  # certificates.
  # This is mainly for very security-sensitive use cases - most users will not
  # need this functionality.
  remove_defaults: false

  # If present, the 'trusted' parameter should contain a certificate (or list
  # of certificates) to add to the system as trusted CA certificates.
  # Pay close attention to the YAML multiline list syntax.  The example shown
  # here is for a list of multiline certificates.

  # adding my own certs because I'm running a local CA and I want my machines to trust my certs by default
  trusted: 
  - |
   -----BEGIN CERTIFICATE-----
   ...
   -----END CERTIFICATE-----
  - |
   -----BEGIN CERTIFICATE-----
   ...
   -----END CERTIFICATE-----
```

I highly recommend all of you to include this into your project as it will keep you from having to configure your VMs individually after boot without having to compromise their integrity. I would also encourage you to look into theh cloud-init documentation to find more usefull data you can pass to your image.
