### DISCUSSION TITLE
posts/pikvm-at-scale/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#230] [Comments]
# posts/pikvm-at-scale/

What is the PiKVM?

https://technotim.live/posts/pikvm-at-scale/

**Comment by TheTechGiant610** [comment]
Hi Tim,

Please you you let me know if you ever get a chance to check the PiKVM V4 against the TESmart 8 port KVM, as I have 2* V3 and both the TESmart & Ezcoo KVMs. I have noticed issues running different clients on the TESmart.

Thank you,
Simon

**Comment by juristoeckli** [comment]
you can use EDID emulators, with hdmi pass trough, like this: https://de.aliexpress.com/item/32948404393.html?spm=a2g0o.productlist.main.3.27d24f020r8PyU&algo_pvid=88997692-8adb-438a-b7b8-ee5878dcbc9d&algo_exp_id=88997692-8adb-438a-b7b8-ee5878dcbc9d-1&pdp_npi=3%40dis%21CHF%2116.47%219.06%21%21%21%21%21%40211bf55216827135079034318d080d%2166264865216%21sea%21CH%21705762502&curPageLogUid=otV6Hx67Vrrr

This way you can use the 8Port KVM switch and override its edid. but you need and edid emulator for every input on the kvm, so 8 pice.

**Reply by timothystewart6** [reply]
Thank you!  This ended up being the fix!

**Comment by Wdeb1** [comment]
For each sudo command you wish to call upon in the GPIO menu you build, you need to grant it in the file /etc/sudoers.d/99_kvmd
Lines to add: 
kvmd ALL=(ALL) NOPASSWD: /usr/bin/reboot
kvmd ALL=(ALL) NOPASSWD: /usr/bin/systemctl

**Comment by NateDiTo** [comment]
I was able to get the Tesmart 8 port KVM to work albeit not on the first try or without tinkering (ALOT), here's how:

# Devices Used/Purchased:

Pikvm v4 Plus

TESmart 8 port KVM: https://buytesmart.com/products/tesmart-8-port-hdmi-kvm-switch-autoscan-rackmount-ethernet-usb-hub-4k-30hz

EDID Emulators (thanks for the suggestion ^^ @juristoeckli): https://www.amazon.com/dp/B07YMNDZT8?ref=ppx_yo2ov_dt_b_product_details&th=1

# EDID Fix (for me)
The EDID issue Techno Tim was experiencing was present for me but not the biggest issue I faced, once I followed TESmart's guide for EDID training guide in one of their videos for this device, everything worked as intended even after many power cycles for all devices in random orders including the KVM Switch itself. 

The only time I have this issue is when unplugging and re-plugging in devices. When I need to do that, I simply repeat the same EDID training step by step in order found in the video linked just below. 

EDID Training: https://www.youtube.com/watch?v=w56QCshaiNQ&t=617s
(Skip to 16:30)

I did end up buying some EDID emulators listed above because in my case the Linux machines were being particularly difficult with this issue at times. I'm not sure if I actually needed them in the end but since I've had everything working for a few weeks now I don't want to mess with it and rock the boat lol. The EDID Emulators are only being used on my 4 linux machines into the kvm switch (I have 7 devices in total being used | 1 Mac, 2 Windows, 4 running different flavors of linux). 

I've done dozens of power cycles for testing of all devices out of order ad infintium (including the kvm switch) as is needed during homelab-ing and there are no EDID issues present as long as the HDMI cables remain connected. Things all work even after power loss as I was also setting up WOL and testing that feature after it was all installed so power was fully removed during that testing and once booting my entire rack back up, everything was still flawless. 

Once the setup was installed in my rack and working correctly I haven't had any issues with this setup at all and it's amazing. (The ventoy USB add was a nice touch). 

# Issue I had with TESmart Switch (probably specific to device I received) + Solution
The biggest issue I faced was that the TESmart switch which I received was NOT setup with the default IP settings out of the box like it should have been (192.168.1.10). This made controlling HDMI switching over IP impossible. I suspect that they sent me a returned device or one that was RMA'd, who knows. I also purchased the unit directly from TESsmart's website and not a 3rd party seller which was even more disappointing.  

The most upsetting part is unless you know what the specific static IP was set to (if it's not default), you cannot interface with it to change it and there is no way I found to query it without a serial connection. (Cable not included with device)

I reached out to their support but didn't get a response in a timeframe I was happy with (to their credit I found a way to make my own serial cable from an old USB to Console cable I had laying around in less than 24 hours from initial ticket submission). Once I had a serial connection to the KVM and interfaced using their software provided on their website (Only on Windows), I was able to revert the KVM to the network I am using. Hopefully this isn't the case for you as there is also no way to query the device for what IP it is using without their serial 3 pin connection, which isn't included, to be able to change it to whatever IP network is running on if it does not come to you with the default IP which should have been 192.168.1.10 

Once I was able to set the IP of the TESmart to the static IP I needed for my network configuration, I was able to control it through the PiKVM and everything worked from there. 

# PiKVM Configuration

FIRST, if you just got your PiKVM, follow the setup guide provided on their website prior to moving on to these options. 

https://docs.pikvm.org/first_steps/

I followed a IP config guide for the Pikvm network and setup I found by apalrd's adventures here (credit to them):

Video: https://www.youtube.com/watch?v=jmwSfUyKC1Q&t=11s

Their post: https://www.apalrd.net/posts/2023/hdmi_kvm/

#IF YOUR HOME/WORK NETWORK CONFIG IS DIFFERENT THAN THE STANDARD 192.168.1.X, THE KVM SWITCH AND THE FOLLOWING CONFIG FILES WILL NEED TO REFLECT YOUR NETWORK FOR THIS TO WORK & WILL NEED TO MATCH WHAT YOU SET THE KVM SWITCH'S STATIC IP TO#

The network configuration goes in /etc/systemd/network/eth0.network

enable read/write
```
rw
```
go to edit the file

```
sudo nano /etc/systemd/network/eth0.network
```
Fill out the information that matches your network/KVM Switch setup

```
[Match]
Name=eth0

[Network]
DHCP=yes
DNSSEC=no
##Use DHCP for primary address
##Add a static address in a /31 for the TESmart KVM
Address=192.168.1.11/31

[DHCP]
##Use same IP by forcing to use MAC address for clientID
ClientIdentifier=mac
##https://github.com/pikvm/pikvm/issues/583
RouteMetric=10
```
Press "Ctrl+X" to Exit

Press "Y" to save

Press "Enter" to confirm

switch back to read-only

```
ro
```

Once I got the IP config setup correctly on the Pikvm & TESmart switch, everything worked as intended. 

# GPIO Config & Layout
For my GPIO layout in the override.yaml file

I used a combination of what TechnoTim provided on this page and the apalrd's adventures linked just above who also used this same setup.

This config was only really possible because of the foundational work that TechnoTim & apalrd's adventures did for me. I made slight edits to what each of them did to fit my use case but the credit goes to them on this. 

enable read/write
```
rw
```
go to edit the file
```
sudo nano /etc/kvmd/override.yaml
```
fill in your information to fit this for the Static IP you set for the tesmart, device naming in the bottom scheme, wake-on-lan mac addresses (if applicable) etc...

```
kvmd:
    gpio:
        drivers:
            tes:
                type: tesmart
                host: 192.168.1.10
                port: 5000
            wol_server0:
                type: wol
                mac: 8a:bf:f2:c8:73:77
            wol_server1:
                type: wol
                mac: 8b:bf:a9:c1:79:81
            reboot:
                type: cmd
                cmd: [/usr/bin/sudo, reboot]
            restart_service:
                type: cmd
                cmd: [/usr/bin/sudo, systemctl, restart, kvmd]
        scheme:
            server0_led:
                driver: tes
                pin: 0
                mode: input
            server0_switch:
                driver: tes
                pin: 0
                mode: output
                switch: false
            server1_led:
                driver: tes
                pin: 1
                mode: input
            pikvm_led:
                pin: 0
                mode: input
            server1_switch:
                driver: tes
                pin: 1
                mode: output
                switch: false
            server2_led:
                driver: tes
                pin: 2
                mode: input
            server2_switch:
                driver: tes
                pin: 2
                mode: output
                switch: false
            server3_led:
                driver: tes
                pin: 3
                mode: input
            server3_switch:
                driver: tes
                pin: 3
                mode: output
                switch: false
            server4_led:
                driver: tes
                pin: 4
                mode: input
            server4_switch:
                driver: tes
                pin: 4
                mode: output
                switch: false
            server5_led:
                driver: tes
                pin: 5
                mode: input
            server5_switch:
                driver: tes
                pin: 5
                mode: output
                switch: false
            server6_led:
                driver: tes
                pin: 6
                mode: input
            server6_switch:
                driver: tes
                pin: 6
                mode: output
                switch: false
            server7_led:
                driver: tes
                pin: 7
                mode: input
            server7_switch:
                driver: tes
                pin: 7
                mode: output
                switch: false
            wol_server0:
                driver: wol_server0
                pin: 0
                mode: output
                switch: false
            wol_server1:
                driver: wol_server1
                pin: 0
                mode: output
                switch: false
            reboot_button:
                driver: reboot
                pin: 0
                mode: output
                switch: false
            restart_service_button:
                driver: restart_service
                pin: 0
                mode: output
                switch: false
        view:
            table:
                - ["TESMART Switch"]
                - []
                - ["#PC1", server0_led, server0_switch|Switch, "wol_server0 | WoL"]
                - ["#MAC", server1_led, server1_switch|Switch]
                - ["#LINUX1", server2_led, server2_switch|Switch]
                - ["#LINUX2", server3_led, server3_switch|Switch]
                - ["#LINUX3", server4_led, server4_switch|Switch]
                - ["#LINUX4", server5_led, server5_switch|Switch]
                - ["#MAINPC", server6_led, server6_switch|Switch, "wol_server1 | WoL"]
                - ["#Test3",  server7_led, server7_switch|Switch]
                - ["#PiKVM", pikvm_led|green, "restart_service_button|confirm|Service", "reboot_button|confirm|Reboot"]
```
Press "Ctrl+X" to Exit

Press "Y" to save

Press "Enter" to confirm

switch back to read-only
```
ro
```

reboot the pikvm or services to see if changes worked and start testing. 

mac addresses, naming of devices, & the KVM Static IP in my config were either randomized or set to default in my example because, privacy. lol

# Restart & Reboot Buttons In GPIO Menu Permissions
For the "Restart" & "Reboot" buttons in the config above, I had to edit the sudo commands to call on. 

Credit goes to @Wdeb1 in the comments on this page for this one. 

For each sudo command you wish to call upon in the GPIO menu you build, you need to grant it in the file /etc/sudoers.d/99_kvmd
Lines to add:

enable read/write
```
rw
```
Then go to edit the file
```
sudo nano /etc/sudoers.d/99_kvmd
```
add these lines to the existing information already present (if applicable)
```
kvmd ALL=(ALL) NOPASSWD: /usr/bin/reboot
kvmd ALL=(ALL) NOPASSWD: /usr/bin/systemctl
```
Press "Ctrl+X" to Exit

Press "Y" to save

Press "Enter" to confirm

switch back to read-only
```
ro
```
Reboot the PiKVM or restart the services and see if those buttons work appropriately. 


Again, massive thank you to @timothystewart6 , my homelab would be nothing compared to what it is without your amazing content and helpful guides. 

Hope this helps someone. 


P.S. if you're also trying to implement Wake-On-Lan with this device and haven't done that yet, make sure to set aside a couple days of pulling your hair out to get it all working correctly if you aren't well versed in WOL yet. I know I spent about 10-20 hours to get that up and running as well. 

# 1st Github Post LETS GO!
