### DISCUSSION TITLE
posts/reverse-proxy-kubernetes/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#231] [Comments]
# posts/reverse-proxy-kubernetes/

Documentation for Techno Tim YouTube videos for all your copy pasta needs!

https://technotim.live/posts/reverse-proxy-kubernetes/

**Comment by aaronjlawson** [comment]
Tim, thanks so much for this write up. Could you help me out regarding the MetalLB address pools. How do you determine what the right addresses are for this block in particular. I'm newer to the networking side of the house regarding platform infastructure.

```
address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250
```
Thanks for your help
