### DISCUSSION TITLE
Traefik SSL Reverse Proxy

### DISCUSSION THREAD

**Discussion by evanlalo** [techno-tim/techno-tim.github.io#252] [Questions]
Hi, thanks for all the great content! Very Inspiring!

I followed the "SSL on Everything" tutorial and I'm running into an issue.

## Overview

I have a domain on Cloudflare. I created 2 TXT records with my domain.

- local.mydomain.com
- *.local.mydomain.com

I also created a DNS record for the machine which is running Traefik as follows, I'm not sure how this relates though.

- athena.local.mydomain.com 

When I run `docker-compose up` everything runs fine.

- I get my certificates in `acme.json`
- I don't receive any errors in the logs
- Also, if I type in the address of my DNS record in Pi.Hole, I get the 404 page from traefik so I'm pretty sure it's working.

When I try to navigate to my dashboard I get the following

```
This site can’t be reached traefik.local.mydomain.com’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED
```

Here's my docker-compose

``` yaml
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL={my email}
      - CF_API_KEY={my key}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/username/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/username/traefik/data/acme.json:/acme.json
      - /home/username/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.mydomain.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:password"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.local.mydomain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.mydomain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.mydomain.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
```

My traefik.yml

``` yaml
api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: {my email}
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
```

I'm so close, I just can't figure out what the problem is.

Any help would be greatly appreciated.

Thanks!

## Update

I changed my DNS record in pi.hole to be the same as the url I defined for my dashboard.

traefik.local.mydomain.com

That now works, however, I'm met with a 404 from Traefik.

<img width="938" alt="Screen Shot 2023-05-17 at 10 46 51 AM" src="https://github.com/techno-tim/techno-tim.github.io/assets/24901654/d9d5e2b8-aa9d-4d9d-88dd-cbc441879762">
