### DISCUSSION TITLE
posts/netbootxyz-tutorial/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#282] [Comments]
# posts/netbootxyz-tutorial/

Imagine all of your favorite operating systems in one place, available anywhere on your network, and you’ll never need to use your flash drive again. That’s the promise of netboot.xyz, a network boot service that lets you install or boot to any operating system simply by booting to the network.

https://technotim.live/posts/netbootxyz-tutorial/

**Comment by Axsgranted** [comment]
Thanks for the write up Tim. While I already had this implemented, I hadn't dug into the Windows portion yet.  Now that I have a, a couple of comments I hope you'll find useful.  I copied the lines with comments relevant to those lines below:

1.(Create working files) with command "copype amd64 C:\WinPE_amd64"
  Comment: Because the folder exists already from previous steps, you'll get an error.  You need to delete this folder which is now empty or use a different folder name.
2. "Then copy the contents of WinPE_amd64.iso to your WinPE folder"
  Comment: Could help to clarify which WinPE folder you're referring to.  The one within netbootxyz container or the WinPE_amd64 folder created when making the ISO.
3. "Then you’ll want to create an SMB share named Windows in your environment. You can create a Windows ISO by visiting Microsoft’s site"
  Comment: Why are we creating an ISO? For the "retail" ISO copy, you just download it.
4. "...you can then extra the files to the root of the Windows share you just created above."
  Comment: I believe you mean "...you can then extract" not "...extra".

**Reply by timothystewart6** [reply]
Thanks for the feedback!   I made the changes!

**Comment by codedmayor** [comment]
Hi Tim, 
I am a huge fan of your Youtube channel and blog.  Can you please do a video of using netboot.xyz with windows? The steps are a bit confusing. And I haven't seen anyone do a video on it yet. Thank you for all you do.

**Reply by erasma** [reply]
I second that

**Reply by timothystewart6** [reply]
Thank you both.  This is good feedback.  In the meantime, can you tell me which part of the Windows section you are stuck on so I can make that better?

**Reply by erasma** [reply]
I think what's not clear is how this works with Windows. As I understand it - we creating a WinPE ISO which starts the windows boot & then the files for the installing windows is done through an SMB share where the windows ISO is extracted.

it's rather a strange concept as apposed to the ISO on a USB

**Reply by jaromirrivera** [reply]
I agree it is strange but it is based on the official docs from netboot.xyz... https://netboot.xyz/docs/kb/pxe/windows

**Comment by jaromirrivera** [comment]
I was able to follow the steps for Windows installs, but when I try to perform the actual install I get the "This PC Can't Run Windows 11" dialog box, even though I setup the VM with a TPM and UEFI in Proxmox. Once I do the TPM Bypass steps with regedit the install goes through...

**Reply by jaromirrivera** [reply]
Great video though!

**Reply by jaromirrivera** [reply]
I was able to figure out the automatic install of Windows!

First I edited the windows.ipxe file and add the following under the line:
```
kernel http://${boot_domain}/wimboot
```
Add the following:
```
initrd ${win_base_url}/configs/auto.bat auto.bat
initrd ${win_base_url}/configs/winpeshl.ini winpeshl.ini
```

Now create the auto.bat and winpeshl.ini files under the win_base_url/configs folder on your netboot.xyz server or container. It should be at the same level as your container's /assets/WinPE/x64 folder. You'll end up having /assets/WinPE/x64 and /assets/WinPE/configs. Create the configs folder if its not there.

auto.bat - contents 
```
@echo off
echo Removing restrictions
for %%s in (sCPU sSecureBoot sTPM) do reg add HKLM\SYSTEM\Setup\LabConfig /f /v Bypas%%sCheck /d 1 /t reg_dword
echo Initializing network
wpeinit
echo Connecting to Shared Drive
net use \\$SERVER\$SHARE /user:$USERNAME $PASSWORD
echo Running Setup.exe
REM \\$SERVER\$SHARE\setup.exe
\\$SERVER\$SHARE\setup.exe /unattend:\\$SERVER\$SHARE\autounattend.xml
```
Note: Remember to replace variables with your own values.

winpeshl.ini - contents
```
[LaunchApps]
"auto.bat"
```

Now just select the normal Windows -> Install option from netboot.xyz and it is fully automated.

Note: I used the following website to generate a *autounattend.xml* file: https://www.windowsafg.com/win10x86_x64_uefi.html

**Reply by Onoitsu2** [reply]
If you know what you're doing, you can even integrate the VirtIO drivers into said install media. Speaking of the dism command and having mounted the .wim, and using /add-driver on your folder having said VirtIO drivers.

**Reply by jaromirrivera** [reply]
Yup, thats what I did install is fully automatic now as it has all the drivers to proceed (storage, network, etc.)

**Reply by SteeveTouil** [reply]
Thanks for sharing your solution for automating the process. Is there any way to ask for user input to choose between windows 10 and 11 ? Maybe when connecting to the share and then saving this choice to run the setup.exe

**Reply by Onoitsu2** [reply]
@SteeveTo You could edit the menus in the PXE server to present more than one option, so you have different items it loads from one version per folder, or you could maybe even have the batch prompt and get a user response, and runs the appropriate setup perhaps. But that might not work across different versions of the boot.wim it loads into. I know Windows 10 was rather picky about that.

**Comment by peracchi** [comment]
Tried to use netboot.xyz offline as you showed in https://www.youtube.com/watch?v=4btW5x_clpg&t=1132s but using Arch Linux instead of PopOS.

I downloaded the three "archlinux-32" assets (airootfs.sfs / initramfs-linux.img / vmlinuz-linux) and also changed "set live_endpoint https://github.com/netbootxyz" to "set live_endpoint http://my.local.ip:8080".

But it not worked, downloaded (slowly like a slug) the files from Internet instead of using the local assets...

Any ideas of what I need to do/change to works like you showed for PopOS?

**Comment by erasma** [comment]
I have it loading Windows install - some trial and error 
The issue I am now having is when I try install on a Proxmox VM I don't see any Drives - I have tried different Drive types I know VirtIO windows does not understand - anyone with a working setup for Proxmox VM?

Also setting it to EFI in the DHCP does not work keep getting access denied not sure why

PS love the channel and work thank you

**Reply by erasma** [reply]
It's working - using EFI - the issue with Proxmox is using Pre-Enroll Keys 

When Creating the VM tick Advanced and untick Pre-Enroll Keys when setting up the VM also don't select VirtIO use the default scsi

Hope this helps someone

**Comment by Onoitsu2** [comment]
Windows mount automation info is as follows. Including bonus usage of Unattended.xml

Where you have your Windows files like bootmgr, bootmgr.efi, setup.exe, 
Create 2 files winpeshl.ini and whatever.bat

Within winpeshl.ini put
```
[LaunchApps]
"whatever.bat"
```
Within your whatever.bat
```
@echo off
echo Initializing network
wpeinit
echo Connecting to Shared Drive
net use \\IP/host.com\FOLDER /user:USERNAME PASSWORD
echo Running Setup.exe
\\IP\FOLDER\setup.exe /unattend:\\IP\FOLDER\autounattend.xml
```

**Reply by erasma** [reply]
Can you help?
Where you have your Windows files like bootmgr, bootmgr.efi, setup.exe,? is this /assets/WinPE/x64/ or the SMB Share?

**Reply by Onoitsu2** [reply]
Technically one in the same depending on your setup, but with their video you'll need 2 locations. Or you'd need to use another method of making that SMB share, overlaid with your netbootxyz assets for windows location respectively. so another container could facilitate sharing just that folder, or you can share it via other means.

**Reply by erasma** [reply]
Sorry might be at cross purposes - I have the PXE WinPE_amd64.iso contents loaded in the docker /assets/WinPE/x64/ location - I then have an SMB folder with my Win install. So when it boots its boots from the docker contents and then needs me to put in the SMB info. These 2 files to auto run the use net I assume that is loaded on the Docker location?

**Reply by Onoitsu2** [reply]
Yes, I have been PXE booting, not from docker, but other PXE boot methods and this is how to automate the mounting of the share.

You can use another docker image to share your /assets/WinPE/x64/ folder if you set things up right, using something like https://hub.docker.com/r/jenserat/samba-publicshare
and having your whatever.bat info reflect that for the correct paths as well, IP or domain name as applicable.

I have in my SMB share, and the docker using a different method as it is actually a Windows SMB share mounted that my docker drops data files into for some tasks.

**Comment by SprintMBrannelly** [comment]
Honestly..... dissapointed. Your intro said that you had done all the hard work researching and this video will show me how to stop having to use usb keys for various ISO's however it didn't really. My typical day runs installing all sorts of OS's from truenas, VMWare, Windows pfsense etc. I do find myself daily creating a usb key for something new i haven't used before and i have a ton of them on  a keyring. I was hoping this would be as easy as create a menu item and point it to an ISO but it actually looks like more work than that. Take the windows example. Having to create a pre-ex environment first. Think ill just keep imaging for now until someone makes a more detailed video on the subject

**Reply by timothystewart6** [reply]
I'm sorry you misinterpreted how this works.  I never mentioned any of those custom / proprietary distributions except Windows, and that's documented.  All of them should be possible but it's going to take some work on your part.  If you'd like to see more distros supported or you've figured out how to create and customize the menu to support these, I would encourage you to contribute to netboot.xyz doc's or code.

**Reply by erasma** [reply]
@SprintMBrannelly 
thats a bit of a shitty attitude - why not try follow the guide and then ask for help when stuck
the guide works i have it up and running with windows - read over the guide a few times

no one has to put these video and guides up so be thankful for whats been published.

**Reply by codedmayor** [reply]
@SprintMBrannelly
That's a terrible way to encourage someone who took his time out to make a video on something that could make your life easy. smh 
You can look into iventoy. I think it's much more easier. You don't need to convert the ISO to any other format. It also has options to include your autounattended.xml file to automate things. It's a pretty cool project. https://iventoy.com/en/index.html

**Reply by Axsgranted** [reply]
If you're going to be disappointed, be disappointed in the state of the tech, not the person trying to help...

**Reply by h7sj** [reply]
@SprintMBrannelly has a fair perspective in my opinion (the YouTube thumbnail was misleading - we have to admit. It literally says "Say goodbye to your flash drives"). HOWEVER - this is just the reality of reaching people on YouTube. This doesn't take anything away from the excellent work @timothystewart6 has done though.

Thanks to Tim planting the seed, I think I have found a solution that genuinely replaces my flash drives and I couldn't be happier - Thank you Tim!

Using the `sanboot` command, I've been able to boot non-free stuff like Macrium and even the Windows 10 installer without any of the complex configuration shown in other replies. This seems to be a poor-man's solution to booting any ISO.

The only problem is it will appear to hang on a black screen for quite a while (10 mins for Windows) while it pulls the entire image to ram.

In my custom `menu.ipxe` configuration:

```
:macrium
echo Starting Macrium
sleep 2
set base-url ${boot-url}/images/macrium
sanboot ${base-url}/MacriumRescue.iso
boot || goto failed
```

**Reply by Onoitsu2** [reply]
@h7sj sanboot is just another way of it loading these files instead of several other methods. Some networks that is good on, and hardware and image combinations, but not all, your experiences may vary drastically. So I offer both ways when I was using an advanced boot menu on my network. But it is much more pared down lately, so only have 2 images anymore. But you can do things like this for faster HTTP transfers, FTP file servers even, and then TFTP it can work in so many ways.

```
:label
initrd ${boot-url}/PXE/iso/FILE.iso || initrd ${boot-url-ftp}/iso/FILE.iso || initrd /iso/FILE.iso
chain ${boot-url}/PXE/memdisk iso raw || chain ${boot-url-ftp}/memdisk iso raw || chain /memdisk iso raw || goto failed
goto start
```

**Reply by SprintMBrannelly** [reply]
You seem to have struggled to understand my grievances. I did follow the guide exactly and had no issue getting it working. It's just that the result failed to live up to the intros claims of me throwing away and never having to image a USB key again As an IT admin this is gold if you can deliver a solution that I can simply dump a heap of ISO's into a folder and have them presented in PXE boot. However, that is not what this does at all. It simply gives you access to live cd's which honestly, I use a couple a times a year. Windows11, Server ubuntu, ESXI, Veeam recovery, Truenas, that's my typical use case and I know I can tinker away and get it working however that's not why I watched this video. Clickbait is ruining the internet and wasting people's time. I'm sure it took Tim a lot of time to prepare this and put it together and I appreciate that and how simple it was to get it up and running, however just didn't ilve up to me throwing away my keys just yet!!

**Reply by mikecarr** [reply]
Not sure your use case but this works perfectly for me. I had a Ventoy USB stick that I would walk around with (my homelab) but now I no longer need it. So in my case it was very accurate and helpful. Just because it doesn't satisfy your needs 100% does not make it click bate or misleading.

"You can't make everyone happy!
You're not a Taco"

**Comment by m9ac** [comment]
I saw your Youtube video of this literally one day too late for it to have been super helpful recovering a Ubuntu server that wouldn't boot. The only thing it would do was enter the iPXE menu, which I had no idea about because ubuntu is pretty stable, and iv'e never seen it unable to boot. since then I have been trying to get netbootxyz up and running in my homelab. I have the docker container running and can access the web gui and have gotten my router set up (edgerouter) per the instructions but for some reason, DHCP options are not being passed to the netboot server. I'm going to keep trying until I get it, but in the meantime, I noticed that there is a very short writeup about getting netbootxyz to run the TFTP sever. and it seems to work. BTW, I really like the look and feel of  this gisgus. I use Disqus on my site and have been dissatisfied with it from the start. I will see if I can easily integrate it. I don't know if it's your speed, based on the quality of your content, but my site is also tech related--mostly focused on helping others access the world of networking technologies (Cisco and the like). Check it out if youre inclined. Here is a post I did a while back that aptly makes me look like I know what im doing, (I think)  https://micah.cerasani.net/take-a-rest/ . 

Anyway, thanks for all your continued hard work and content

**Comment by m9ac** [comment]
turns out, the documentation for edgeOS/vyos found here on the linux.io site (https://docs.linuxserver.io/images/docker-netbootxyz/?h=netboo#opnsense)  is either worthless or my router doesn't support that particular configuration. instead, I used part of the config from the netbook.xyz site (https://netboot.xyz/docs/kb/networking/edgerouter) 

three set commands and I was off to the races. Here they are for anyone interested (You will need to adjust the ip addresses for you environment.):

edit service dhcp-server shared-network-name LAN subnet 10.0.0.0/24
set bootfile-server 10.0.0.20
set bootfile-name netboot.xyz.kpxe

HTH

**Comment by mikecarr** [comment]
I just found something else odd, I have to change the NIC's MAC address when trying to start the same VM multiple times otherwise the command 'net use.....' does not work.

Now that I got passed that, the next issue is that I get an error when the installer is "Copying files", error "Windows could not apply the unattend answer file's «DiskConfiguration> setting"

**Reply by mikecarr** [reply]
Got past that and I am running now!! I changed the SCSI Controller to Virtio SCSI

**Comment by bedge117** [comment]
Hi Tim,

I am sure you would make this look like child's play, like you do everything!!!  Your videos have been extremely helpful, and I look forward to your new videos more than any other outlet I am subscribed to.

I wanted to pass this along to all of the UDM Pro/SE users out there.  **(I actually switched to UDM because of your video, and I haven't looked back!)**

# On the UDM Pro/SE

## Changes made to the "/run/dnsmasq.conf.d/" folder are not persistent.  These are modified instructions to keep your configuration persistent on boot.

### First, SSH into your UNIFI Dream Machine.  
(Working as of version Network: 8.0.7 UniFi OS 3.1.16) 11/18/2023

It is ok to stay in your home directory for this first command.  If you are not currently in the home folder, navigate there by doing:
```
cd ~
```
*note, the above step is not required, but it makes you feel more warm and fuzzy.  Don't want to leave out any details.*


Instructions can be found here:  [Unifi-utilities on-boot-script](https://github.com/unifi-utilities/unifios-utilities/tree/main/on-boot-script)

Now that you are in your home directory, the next step is installing the **on-boot-script** provided by unifi-utilities.

The easiest Method is to execute the following command:
```
curl -fsL "https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh
```

*There are also manual methods and upgrade methods if you have previously installed on-boot-script, or you are not comfortable using `curl` but I will not cover that here.  Reference the [github](https://github.com/unifi-utilities/unifios-utilities/tree/main/on-boot-script) for more info.*

### Now that on-boot-script has been installed, navigate to 
```
cd /data/on_boot.d/
```
Issue the next commands:
```
vi nameofyourfile.sh
``````
**replace `nameofyourfile` with the name of the script you are creating.**

You are now in vi editor.  *Don't worry, I know it's not **nano**, but I'll walk you through it.*

You should be in a blank file *unless you are modifying your script.*

To edit, simply press the `i` key on your keyboard.

Now enter the following for your PXE.conf file.

```
#!/bin/bash
cat > /run/dnsmasq.conf.d/PXE.conf <<- "EOF"
#Created by a UDM-Utilities run script
#Configuration of PXE boot for '

#The boot filename, Server name, Server Ip Address
dhcp-boot=netboot.xyz.kpxe,netboot.xyz,192.168.0.1
#inspect the vendor class string and match the text to set the tag
dhcp-vendorclass=BIOS,PXEClient:Arch:00000
dhcp-vendorclass=UEFI32,PXEClient:Arch:00006
dhcp-vendorclass=UEFI,PXEClient:Arch:00007
dhcp-vendorclass=UEFI64,PXEClient:Arch:00009
#Set the boot file name based on the matching tag from the vendor class (above)
dhcp-boot=net:UEFI32,netboot.xyz.efi,netboot.xyz,192.168.0.1
dhcp-boot=net:BIOS,netboot.xyz.kpxe,netboot.xyz,192.168.0.1
dhcp-boot=net:UEFI64,netboot.xyz.efi,netboot.xyz,192.168.0.1
dhcp-boot=net:UEFI,netboot.xyz.efi,netboot.xyz,192.168.0.1
EOF
#Restart dnsmasq so it sees the new conf file
kill -9 `cat /run/dnsmasq.pid`
```
**Replace `192.168.0.1` with the IP address of your 'netbootxyz' instance.***

The beginning of the syntax above is `#!/bin/bash` (This needs to be line 1)
The end of the syntax above is ```kill -9 `cat /run/dnsmasq.pid` ```(This will be your last line)

**Once you have changed your IP and made your edits, you need to press the `Esc` key on your keyboard. 
*This will take you out of insert "edit" mode.*

Now type `:wq`  This will *"W"rite the file and "Q"uit VI.*

Your file should now be in your `/data/on_boot.d/` folder.  To confirm this, you can type:
`ls`
This will show you a list of all the files in your current directory.

**Your next step** is to **chmod** the file so you can run the `.sh` file.  To do this, simply execute the following command:
`chmod +x nameofyourfile.sh`   
*or whatever you named it.*

### Now, you want to run your script.  
To do this, execute the following command.
``./nameofyourfile.sh`

This will run the script you just created and create a file in the `/run/dnsmasq.conf.d/` folder named `PXE.conf`

This will also automatically restart the dnsmasq process via the command: `kill -9 `cat /run/dnsmasq.pid`

To verify the file is there, execute the following command:
```
cat /run/dnsmasq.conf.d/PXE.conf
``````
This will write out the contents of your file in your terminal.  

## Congratulations!  
### You now have a persistent PXE.conf file that will be recreated on each reboot.  

**Note, the on-boot-script doesn't always carry over after each firmware update.** *Though mine has been successful through the last 4 releases, and I am on the Release Candidate Release Channel.*

The only thing you need to do, *unless unifi makes another breaking change*, is to re-run the script:
`curl -fsL "https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh`

*Your .sh files will still be in the /data/on_boot.d/ folder.*

Hopefully this helps someone!!!

- [x] Watch every single Techno Tim Video
- [x] Post on Tim's Page
- [x] Get a reply from Tim
- [ ] Someday meet Tim :D

**Reply by jwolfera** [reply]
Does this work with the Unifi controller running in Docker?  I'm not cool enough for a UDM LOL.

**Reply by timothystewart6** [reply]
Wow, thank you @bedge117 !  Maybe I will add this to the docs!  Thanks again!

**Reply by bedge117** [reply]
This should. I had it containerized a while back, but I no longer have it since I have a controller. That being said, you should still be able to modify the options in a terminal session. 

Let me know if you try, and if you have any issues, I'd be happy to try to help.

I'll try to spin up a docker container and test it for you real quick. :)

**Comment by rickgitdone** [comment]
local assets can be served by editing the menu ipxe files vise the main boot.cfg so you have the best of both online and local assets as long as you have downloaded local copies. comment out the main link and hard code your local server into the asset link(s)... per below ...

EX: for System Rescue CD

# set url ${live_endpoint}/asset-mirror/releases/download/10.02-a0627929/
set url http://10.10.6.1:8080/asset-mirror/releases/download/10.02-a0627929/
goto boot

**Reply by rickgitdone** [reply]
the comment "#" turned on html code bold sorry for the main link...should have read:
"# set url ${live_endpoint}/asset-mirror/releases/download/10.02-a0627929/"

**Comment by Tensorr** [comment]
Hey Tim, thanks for this.  
this worked great always wanted a PXE server, for some reason the live-cds don't work for me but the installs is the important part and those work fine (haven't tried a win image yet)

As a totally minor comment, I think creating a volume and then using it is simpler, with this docker will create the dir for you and mount it (note that I remebered the convention docker uses for the volumes but used the wrong name as that created the /var/lib/docker/volumes/netboot_netboot_data/_data dir, so stackname_yourname/_data is what it creates). the yaml would be:
```
---
volumes:
  netboot_data: { driver: local }
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
   # environment:
      #- MENU_VERSION=2.0.47 # optional
    volumes:
      - netboot_data:/config # optional
      - netboot_data:/assets # optional
    ports:
      - 4000:3000
      - 69:69/udp
      - 8888:80 #optional
    restart: unless-stopped
```

**Reply by Tensorr** [reply]
aw, sorry left the ports I was using to test it and can't edit them to the std ones

**Comment by deffcolony** [comment]
Hi Tim,

I've developed an automation script that handles the installation of Windows ADK and effortlessly builds the WinPE ISO. The entire process is automated, requiring no manual command inputs. (It is a menu where you can choose what to run) I believe this could be a valuable tool for many users.

https://github.com/deffcolony/ai-toolbox/tree/main/etc/windows

**Comment by codedmayor** [comment]
Is secure boot supported?

**Comment by apwiggins** [comment]
Tim....Great tutorial!  I have an Ubiquiti EdgeRouter where the router needed to be adjusted.  The DHCP server configuration didn't work out of the box, so needed to be updated.  Passing along to anyone that needs it.

https://netboot.xyz/docs/kb/networking/edgerouter/

# Ubiquiti EdgeRouter
This document covers how to setup netboot.xyz, a service that provides iPXE-based installation and live boot of a bunch of operating systems, on a Ubiquiti EdgeRouter.

Thanks go to Sam Kottler for originally writing up this how-to. Improve setup robustness by using the embedded TFTP daemon from dnsmasq by Yan Grunenberger instead of external TFTP package.

**Comment by itdkr** [comment]
Hello Tim,

i want to run a script after the OS (Windows10/11) is installed. How can i do that with netboot.xyz?

The script should install some software.

Regards
Kevin

**Comment by eliaspizarro** [comment]
# compose.yaml
```
version: "3"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./netboot_data:/config
      - netboot-assets:/assets
    ports:
      - ${WEB_APP_PORT}:3000
      - 69:69/udp
      - ${WEB_PXE_PORT}:80
  samba1:
    image: crazymax/samba
    container_name: samba1
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SAMBA_LOG_LEVEL=0
      - SAMBA_HOSTS_ALLOW=${SAMBA_HOSTS_ALLOW}
    volumes:
      - ./samba.yml:/data/config.yml:ro
      - netboot-assets:/samba/share
    networks:
      samba_net:
        ipv4_address: 172.16.239.2
  samba2:
    image: crazymax/samba
    container_name: samba2
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SAMBA_LOG_LEVEL=0
      - SAMBA_HOSTS_ALLOW=${SAMBA_HOSTS_ALLOW}
    volumes:
      - ./samba.yml:/data/config.yml:ro
      - netboot-assets:/samba/share
    networks:
      samba_net:
        ipv4_address: 172.16.239.3
  samba3:
    image: crazymax/samba
    container_name: samba3
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SAMBA_LOG_LEVEL=0
      - SAMBA_HOSTS_ALLOW=${SAMBA_HOSTS_ALLOW}
    volumes:
      - ./samba.yml:/data/config.yml:ro
      - netboot-assets:/samba/share
    networks:
      samba_net:
        ipv4_address: 172.16.239.4
  haproxy:
    image: haproxy:latest
    container_name: samba-haproxy
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - ${SMB_PORT}:445
    networks:
      samba_net:
        ipv4_address: 172.16.239.14
    depends_on:
      - samba1
      - samba2
      - samba3
volumes:
  netboot-assets:
    driver: local
    driver_opts:
      type: none
      device: ./assets
      o: bind
networks:
  samba_net:
    name: samba_net
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/28
```
# .env
```
WEB_PXE_PORT=8080
WEB_APP_PORT=3000
SMB_PORT=445
SAMBA_HOSTS_ALLOW=127.0.0.1 172.16.239.14
TZ=<like America/Santiago>
```
# samba.yml
```
auth:
  - user: netboot
    group: netboot
    uid: 1000
    gid: 1000
    password: netbootxyz
  - user: ro
    group: ro
    uid: 1001
    gid: 1001
    password: ro.2024

global:
  - "force user = netboot"
  - "force group = netboot"
  - "keepalive = 5"
  - "deadtime = 1"
  - "winbind scan trusted domains = No"
  - "disable spoolss = Yes"
  - "dos charset = ascii"
  - "load printers = No"
  - "security = USER"

share:
  - name: assets
    comment: Netboot.xyz assets
    path: /samba/share
    browsable: no
    readonly: no
    guestok: no
    veto: no
    writelist: netboot
    validusers: netboot,ro

```
# haproxy.cfg
```
frontend samba_frontend
    bind *:445
    mode tcp
    default_backend samba_backend

backend samba_backend
    mode tcp
    balance roundrobin
	log global
    server samba1 172.16.239.2:445 check
    server samba2 172.16.239.3:445 check
	server samba3 172.16.239.4:445 check
```
# install.bat
```
@echo off

set SHARE=assets
set SERVER=172.168.64.80
set USR=ro
set PSW=ro.2024

set SO=%1
set UNC=\\%SERVER%\%SHARE%\%SO%

echo .
for %%s in (sCPU sSecureBoot sTPM) do reg add HKLM\SYSTEM\Setup\LabConfig /f /v Bypas%%sCheck /d 1 /t reg_dword

cls
echo ..
wpeinit

:install
cls
echo ...
net use i: %UNC% /user:%USR% %PSW% > nul 2>&1 || goto :install
echo ....
i:
i:\setup.exe
net use /del * /y > nul 2>&1
exit
```

# winpeshl-windows-10.ini
```
[LaunchApps]
install.bat, windows-10
```
...

# windows.ipxe
```
#!ipxe

# Microsoft Windows
# https://www.microsoft.com

set win_arch x64
# Custom configs start
set start_script install.bat
set start_app ${win_base_url}/configs/${start_script}
# Custom config ends
goto ${menu} ||

:windows
set os Microsoft Windows
clear win_version
menu ${os} 
item --gap Installers
item win_install ${space} Load ${os} Installer...
# Custom configs start
item win10 ${space} Install ${os} 10
item win11 ${space} Install ${os} 11
item winsrv19 ${space} Install ${os} Server 2019
item winsrv22 ${space} Install ${os} Server 2022
# Custom config ends
item --gap Options:
item arch_set ${space} Architecture [ ${win_arch} ]
item url_set ${space} Base URL [ ${win_base_url} ]
choose win_version || goto windows_exit
goto ${win_version}

:arch_set
iseq ${win_arch} x64 && set win_arch x86 || set win_arch x64
goto windows

:url_set
echo Set the HTTP URL of an extracted Windows ISO without the trailing slash:
echo e.g. http://www.mydomain.com/windows
echo
echo -n URL: ${} && read win_base_url
echo
echo netboot.xyz will attempt to load the following files:
echo ${win_base_url}/${win_arch}/bootmgr
echo ${win_base_url}/${win_arch}/bootmgr.efi
echo ${win_base_url}/${win_arch}/boot/bcd
echo ${win_base_url}/${win_arch}/boot/boot.sdi
echo ${win_base_url}/${win_arch}/sources/boot.wim
echo
prompt Press any key to return to Windows Menu...
goto windows

:win_install
isset ${win_base_url} && goto boot || echo URL not set... && goto url_set

# Custom configs start
:win10
set winpeshl_ini winpeshl-windows-10.ini
isset ${win_base_url} && goto boot || echo URL not set... && goto url_set

:win11
set winpeshl_ini winpeshl-windows-11.ini
isset ${win_base_url} && goto boot || echo URL not set... && goto url_set

:winsrv19
set winpeshl_ini winpeshl-windows-server-2019.ini
isset ${win_base_url} && goto boot || echo URL not set... && goto url_set

:winsrv22
set winpeshl_ini winpeshl-windows-server-2022.ini
isset ${win_base_url} && goto boot || echo URL not set... && goto url_set
# Custom config ends

:boot
imgfree

# Custom configs start
initrd ${start_app} ${start_script} ||
initrd -n winpeshl.ini ${win_base_url}/configs/${winpeshl_ini} ||
# Custom config ends

kernel http://${boot_domain}/wimboot
initrd -n bootmgr     ${win_base_url}/${win_arch}/bootmgr       bootmgr ||
initrd -n bootmgr.efi ${win_base_url}/${win_arch}/bootmgr.efi   bootmgr.efi ||      
initrd -n bcd         ${win_base_url}/${win_arch}/boot/bcd      bcd ||
initrd -n bcd         ${win_base_url}/${win_arch}/Boot/BCD      bcd ||
initrd -n boot.sdi    ${win_base_url}/${win_arch}/boot/boot.sdi boot.sdi ||
initrd -n boot.sdi    ${win_base_url}/${win_arch}/Boot/boot.sdi boot.sdi ||
initrd -n boot.wim    ${win_base_url}/${win_arch}/sources/boot.wim boot.wim
boot

:windows_exit
exit 0
```

#

**Comment by sherbmeister** [comment]
For windows (which I was most interested in), I got it to the point where the command line pops up and executes "wpeinit".

After that, I can't do anything as aparently my VM does not have an IPs. Can't ping my netboot machine obviously... Could anyone adise?? thanks

**Comment by ikkuranus** [comment]
I was unable to get this to work. Initially I ran into the snag of not having network drivers included in my boot.wim.
After I fixed that I was able to mount the share but now I get an error about the side-by-side configuration being incorrect when setup is run. I'm at a loss here as all the posts related to this recommend reinstalling the application or some other crap that has nothing do with windows installation.

**Reply by ikkuranus** [reply]
nevermind had to use a different image

**Comment by Wesseldr** [comment]
Thanks for the write up Tim.
I was able to get this working on a DS923+ with a little tweak. Below is my full docker-compose file:

```yaml
---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    #environment:
      # - MENU_VERSION=2.0.47 # optional, sets menus version, unset uses latest
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      #- 8088:80 #optional
    network_mode: host   # <--- NEEDED ON SYNOLOGY
    restart: unless-stopped
```
