### DISCUSSION TITLE
posts/advanced-kubernetes-networking/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#316] [Comments]
# posts/advanced-kubernetes-networking/

I just discovered Multus and it fixed Kubernetes networking! In this video we cover a lot of Kubernetes networking topics from beginner topics like CNIs, to advanced topics like adding Multus for more traditional networking within Kubernetes - which fixes a lot of problems you see with Kubernetes networking. Also, I had to turn the nerd up to 11 on this one.

https://technotim.live/posts/advanced-kubernetes-networking/

**Comment by minhdq0302** [comment]
Dear Tim, 
I have a question about Multus implementation on K3S using Cilium CNI. It looks a little bit different with Cilium and RKE2. Have you ever been successfully to implement this case? Thanks in advanced.

**Comment by specious-logic** [comment]
Great video!

Seems like this may not work with k3s. No matter the value for config.cni_conf.confDir in values.yaml it still seems to fail with ```failed to create multus config: cannot find valid master CNI config in "/host/etc/cni/net.d"```

Looking at the rendered template from the helm chart at https://rke2-charts.rancher.io it seems like the DaemonSet is hard coded with
```
      containers
        args:
        - "--multus-conf-file=auto"
        - "--multus-autoconfig-dir=/host/etc/cni/net.d"
        volumeMounts:
        - name: multusautoconfig
          mountPath: /host/etc/cni/net.d
      volumes:
        - name: multusautoconfig
          hostPath:
            path: /etc/cni/net.d
```

I am not exactly a wiz with go templates so I have not dug in further and might even be wrong about the problem. I guess I may just manually alter the helm rendered resources and commit directly to Flux... Was definitely looking forward to killing a few of my LXC containers but need macvlan interfaces to do it.

Thanx!
