### DISCUSSION TITLE
posts/change-detection-docker/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#324] [Comments]
# posts/change-detection-docker/

Tracking things on the web just got a whole lot easier with ChangeDetection, the free and open source Docker container! Track website changes, price changes of products, and even track out of stock products with notifications all from a container you host yourself!

https://technotim.live/posts/change-detection-docker/

**Comment by JarrodHelzer** [comment]
Hi Techno Tim,

Thank you for sharing this video on your channel.  I was thinking about solving this exact problem but had not started researching solutions.  Oddly enough, my exact challenge has been finding a couple Ubiquity items in stock.  I have the solution running and it appears to be working aside from an exception error "Exception:  Target page, context or browser has been closed". 

Been searching like crazy and have not been able to find a resolution.  I've seen suggestions to use another version of Playwright, etc.  Nothing difinitive so far.  If I find something I will post it here.

**Reply by sneak-it** [reply]
Some websites have some anti-robot measures (captcha, various blocks) in place where ChangeDetection will struggle, or you will need to modify headers/user agent to get better results - still figuring this out myself, even from a residential IP.

Best improvement I've had with this issue is indeed using the most up to date version of Playwright **Chromium**, which is the latest recommended version (ChangeDetection needs to update docs). browserless/chrome has not seen updates/pushes in over 4 months. Here is a docker compose that I have working quite well:

```yaml
services:
  changedetection:
    container_name: ChangeDetection
    image: dgtlmoon/changedetection.io:latest
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    networks:
      - changedetectionnet
    ports:
      - 5000:5000
    volumes:
      - /path/to/your/datastore:/datastore:rw
    environment:
     - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
     #- PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/chrome?stealth=1&--disable-web-security=true&blockAds=true - blockAds was causing a few websites to time out
     - BASE_URL=x.x.x.x:1891
    depends_on:
      playwright-chrome:
          condition: service_started
  # https://www.browserless.io/docs/docker
  playwright-chrome:
    hostname: playwright-chrome
    container_name: playwright-chrome
    #image: ghcr.io/browserless/chrome:latest
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    networks:
      - changedetectionnet
    expose:
      - 3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - TIMEOUT=60000 #60 seconds
      - CONCURRENT=4

networks:
  changedetectionnet:
    name: changedetectionnet
    driver: bridge
```
