### DISCUSSION TITLE
posts/immich-self-hosted/

### DISCUSSION THREAD

**Discussion by giscus** [techno-tim/techno-tim.github.io#346] [Comments]
# posts/immich-self-hosted/

Protect your personal photos and videos by hosting them yourself. In this video, you’ll learn how to install Immich, an open-source photo and video platform, on your own home server using Docker. Take control of your data with a fast, modern interface, GPU-accelerated features, and the ability to use your own NAS or network storage.

https://technotim.live/posts/immich-self-hosted/

**Comment by alexbergsland** [comment]
Great guide as always!
This was perfect for me as I have been looking for a good solution, the best I've had before this was Nextcloud in combination with Plex. Just for my girlfriend to be able to easily add pictures and videos and then cast them to the TV.
But I've ditched that now.

I just like to add, if anyone using Portainer and like me want to keep everything in Portainer, no extra env or yml-files.
I got it working after a lot of trial and error.
Here is some info for the environment variables: https://immich.app/docs/install/portainer
Basically you change
```
    env_file:
      - .env
```
to
```
    env_file:
       - stack.env
```
.. and add the variables in Portainer.

You can also in-line the transcoding like this:
```
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
```
I don't seem to find where I found the last bit but it is the immich-documentation somewhere.
