### DISCUSSION TITLE
Grafana Loki Docker Driver for ARM-based servers

### DISCUSSION THREAD

**Discussion by AndreiTelteu** [techno-tim/techno-tim.github.io#97] [Questions] [answered]
Hi
In regards to this article: https://techno-tim.github.io/posts/grafana-loki/
I had a problem trying to capture docker logs on my arm-based server, as soon as i edited daemon.json and restarted the docker service, it wouldn't start.
I had to delete /etc/docker/daemon.json. The loki docker driver does not support arm https://github.com/grafana/loki/issues/1973

I found a solution using vector.dev and i am posting the solution here if anyone else has this problem:
Add the vector service to the docker-compose.yml file
```yml

    vector:
        image: timberio/vector:0.18.1-debian
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/serveradmin/docker_volumes/vector/vector-config.toml:/etc/vector/vector.toml:ro
        ports:
            - "8383:8383"
        restart: unless-stopped
        networks:
            - loki
```

Run this commands
```bash
mkdir vector
cd vector
nano vector-config.toml
```

Paste this config file:
```toml
[sources.docker-local]
  type = "docker_logs"
  docker_host = "/var/run/docker.sock"
  exclude_containers = []
 
  # Identify zero-width space as first line of a multiline block.
  multiline.condition_pattern = '^\x{200B}' # required
  multiline.mode = "halt_before" # required
  multiline.start_pattern = '^\x{200B}' # required
  multiline.timeout_ms = 1000 # required, milliseconds
 
[sinks.loki]
  # General
  type = "loki" # required
  inputs = ["docker*"] # required
  endpoint = "http://loki:3100" # required
  
  # Auth
  auth.strategy = "bearer" # required
  auth.token = "none" # required
  
  # Encoding
  encoding.codec = "json" # required
  
  # Healthcheck
  healthcheck.enabled = false # optional, default
  
  # Loki Labels
  labels.forwarder = 'vector'
  labels.host = '{{ host }}'
  labels.container_name = '{{ container_name }}'
  labels.compose_service = '{{ label.com\.docker\.compose\.service }}'
  labels.compose_project = '{{ label.com\.docker\.compose\.project }}'
  labels.source = '{{ stream }}'
  labels.category = 'dockerlogs'
```

Credits to this post for the config file: https://github.com/grafana/loki/issues/2361#issuecomment-826732810
