### ISSUE TITLE
How to assign a custom port to a new docker container in docker services when using with traefik

### ISSUE THREAD

**Issue by johntheripp3r** [techno-tim/techno-tim.github.io#223]
I am using the SSL on everything guide to get SSL certs for every sub-sub domain services that I want with traefik but I have now 2 services that are exposing port 8080 and I can not seem to change the port to anything else while using this traefik guide.

I am referring to this guide: https://docs.technotim.live/posts/traefik-portainer-ssl/

Here is what my docker-compose looks like:

```
version: '3'
services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    container_name: trilium2
    networks:
      - proxy
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - 8081:8080
    volumes:
      - /home/user/docker/trilium2:/home/node/trilium-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notes.entrypoints=http"
      - "traefik.http.routers.notes.rule=Host(`notes.local.example.com`)"
      - "traefik.http.middlewares.notes-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.notes.middlewares=notes-https-redirect"
      - "traefik.http.routers.notes-secure.entrypoints=https"
      - "traefik.http.routers.notes-secure.rule=Host(`notes.local.example.com`)"
      - "traefik.http.routers.notes-secure.tls=true"
      - "traefik.http.routers.notes-secure.service=notes"
      - "traefik.http.services.notes.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
```
If I add
```
ports:
- 8081:8080
```

then it does not work with this config. Any help?
Thanks.
