### ISSUE TITLE
traefik-portainer-ssl ipWhiteList not in middleware chain (external vs local proxy)

### ISSUE THREAD

**Issue by erlbruch** [techno-tim/techno-tim.github.io#57]
Hi Tim,

i really like your content. Keep up spreading the homelab spirit.

I started my journey to Traefik with the help of [https://github.com/htpcBeginner/docker-traefik](https://github.com/htpcBeginner/docker-traefik). When i saw your video, i thought i could finally proxy all my local services with ssl/tls certificates and also proxy some services externally (e.g Nextcloud).

I noticed that the only thing that keeps your config secure and prevents Traefik from serving your internal sites externally is your router is not forwarding ports 80 and 443 to Traefik (Thanks to the acme dns challenge which works independently of dns A records). You were talking about IP whitelisting of local networks as an additional layer of security if using internally, but it becomes crucial if you port forward to your Traefik instance. Your config does not use the "secured" middleware chain you defined, but uses "default-headers" for all http routers instead.

````
# You created the middleware chain
http:
  middlewares:
    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
  
# But you never referenced it in your routers
http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.example.com`)"
      middlewares:
        - default-headers # should reference "secured" middleware chain
      tls: {}
      service: proxmox
````

Okay, but now how to provide ssl/tls to internal services with wildcard certificates while also beeing able to host some externally (hopefully with the same Traefik instance)? How could I add internal services to Traefik if my Router is allready pointing at Traefik? Does the ipWhiteList middleware provide enough security? Maybe let's figure out together

Best,
Florian
